config/routes.rb
Rails.application.routes.draw do
  resources :students
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:nis, :nama, :jenis_kelamin, :tempat_lahir, :tanggal_lahir, :alamat, :asal_sekolah, :kelas, :jurusan)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudPpdb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nis %>
    <%= form.text_field :nis %>
  </div>

  <div class="field">
    <%= form.label :nama %>
    <%= form.text_field :nama %>
  </div>

  <div class="field">
    <%= form.label :jenis_kelamin, "Jenis Kelamin" %>
    <%= form.radio_button :jenis_kelamin, 'Laki-laki' %>
    <%= form.label :jenis_kelamin, "Laki-Laki", :value => "Laki-laki"  %>
    <%= form.radio_button :jenis_kelamin, 'Perempuan' %>
    <%= form.label :jenis_kelamin, "Perempuan", :value => "Perempuan" %>
  </div>

  <div class="field">
    <%= form.label :tempat_lahir %>
    <%= form.text_field :tempat_lahir %>
  </div>

  <div class="field">
    <%= form.label :tanggal_lahir %>
    <%= form.date_select :tanggal_lahir %>
  </div>

  <div class="field">
    <%= form.label :alamat %>
    <%= form.text_field :alamat %>
  </div>

  <div class="field">
    <%= form.label :asal_sekolah %>
    <%= form.text_field :asal_sekolah %>
  </div>

  <div class="field">
    <%= form.label :kelas, 'Kelas' %>
    <%= form.select :kelas, ['X', 'XI', 'XII'], :prompt => 'Pilih Kelas' %>
  </div>

  <div class="field">
    <%= form.label :jurusan, 'Jurusan' %>
    <%= form.select :jurusan, ['OTKP', 'RPL', 'TKJ', 'BDP', 'TBG', 'HTL'], :prompt => 'Pilih Jurusan' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Nis</th>
      <th>Nama</th>
      <th>Jenis kelamin</th>
      <th>Tempat lahir</th>
      <th>Tanggal lahir</th>
      <th>Alamat</th>
      <th>Asal sekolah</th>
      <th>Kelas</th>
      <th>Jurusan</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.nis %></td>
        <td><%= student.nama %></td>
        <td><%= student.jenis_kelamin %></td>
        <td><%= student.tempat_lahir %></td>
        <td><%= student.tanggal_lahir %></td>
        <td><%= student.alamat %></td>
        <td><%= student.asal_sekolah %></td>
        <td><%= student.kelas %></td>
        <td><%= student.jurusan %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nis:</strong>
  <%= @student.nis %>
</p>

<p>
  <strong>Nama:</strong>
  <%= @student.nama %>
</p>

<p>
  <strong>Jenis kelamin:</strong>
  <%= @student.jenis_kelamin %>
</p>

<p>
  <strong>Tempat lahir:</strong>
  <%= @student.tempat_lahir %>
</p>

<p>
  <strong>Tanggal lahir:</strong>
  <%= @student.tanggal_lahir %>
</p>

<p>
  <strong>Alamat:</strong>
  <%= @student.alamat %>
</p>

<p>
  <strong>Asal sekolah:</strong>
  <%= @student.asal_sekolah %>
</p>

<p>
  <strong>Kelas:</strong>
  <%= @student.kelas %>
</p>

<p>
  <strong>Jurusan:</strong>
  <%= @student.jurusan %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>